Portal.Web/Areas/Admin/Controllers/AccountsController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Portal.Application.Abstraction;
using Portal.Domain.Entities;
using Portal.Domain.Entities.Interfaces;
using Portal.Infrastructure.Identity;
using Portal.Infrastructure.Identity.Enums;

namespace Portal.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = nameof(Roles.Admin) + ", " + nameof(Roles.Manager))]
    public class AccountsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public AccountsController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Accounts()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }

        public async Task<IActionResult> DeleteAsync(string Id)
        {
            var user = await _userManager.FindByIdAsync(Id);
            if (user == null)
            {
                return NotFound();
            }
            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Accounts));
            }
            else
            {
                return View("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync(string Id)
        {
            var user = await _userManager.FindByIdAsync(Id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(User user)
        {
            if (ModelState.IsValid)
            {
                var existing = await _userManager.FindByIdAsync(user.Id.ToString());
                if(existing == null)
                {
                    return NotFound();
                }
                existing.UserName = user.UserName;
                existing.FirstName = user.FirstName;
                existing.LastName = user.LastName;
                existing.Email = user.Email;
                existing.PhoneNumber = user.PhoneNumber;

                var result = await _userManager.UpdateAsync(existing); 

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Accounts));
                }
                else
                {
                    return View("Error");
                }
            }

            return View(user);
        }
    }
}

Portal.Web/Areas/Admin/Controllers/AkceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Portal.Application.Abstraction;
using Portal.Domain.Entities;
using Portal.Infrastructure.Database;
using Portal.Infrastructure.Identity.Enums;

namespace Portal.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = nameof(Roles.Admin) + ", " + nameof(Roles.Manager))]
    public class AkceController : Controller
    {
        IAkceAdminService _akceAdminService;
        public AkceController(IAkceAdminService akceAdminService)
        {
            _akceAdminService = akceAdminService;
        }

        public IActionResult Akce()
        {
            IList<Akce> akces = _akceAdminService.Select();
            return View(akces);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(Akce akce)
        {
            _akceAdminService.Create(akce);

            return RedirectToAction(nameof(AkceController.Akce));
        }

        public IActionResult Delete(int Id)
        {
            bool deleted = _akceAdminService.Delete(Id);

            if (deleted)
            {
                return RedirectToAction(nameof(AkceController.Akce));
            }
            else
                return NotFound();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Akce? akce = _akceAdminService.Select().FirstOrDefault(ak => ak.Id == id);

            if (akce == null)
            {
                return NotFound();
            }

            return View(akce);
        }

        [HttpPost]
        public IActionResult Edit(Akce akce)
        {
            if (ModelState.IsValid)
            {
                _akceAdminService.Update(akce);
                return RedirectToAction(nameof(Akce));
            }

            return View(akce);
        }
    }
}

Portal.Web/Areas/Admin/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portal.Application.Abstraction;
using Portal.Domain.Entities;
using Portal.Infrastructure.Identity.Enums;

namespace Portal.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = nameof(Roles.Admin) + ", " + nameof(Roles.Manager))]
    public class OrderItemController : Controller
    {
        IOrderItemService _orderItemService;
        IAkceAdminService _akceService;
        IOrderService _orderService;
        public OrderItemController(IOrderItemService orderItemService, IAkceAdminService akceService, IOrderService orderService)
        {
            _orderItemService = orderItemService;
            _akceService = akceService;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            IList<OrderItem> orderItems = _orderItemService.Select();
            return View(orderItems);
        }

        [HttpGet]
        public IActionResult Create()
        {
            SetOrderAndAkceSelectLists();
            return View();
        }

        [HttpPost]
        public IActionResult Create(OrderItem orderItem)
        {
            if (ModelState.IsValid)
            {
                _orderItemService.Create(orderItem);
                return RedirectToAction(nameof(OrderItemController.Index));
            }
            else
            {
                SetOrderAndAkceSelectLists();
                return View(orderItem);
            }
        }

        void SetOrderAndAkceSelectLists()
        {
            IList<Akce> akces = _akceService.Select();
            ViewData[nameof(OrderItem.AkceID)] = new SelectList(akces, nameof(Akce.Id), nameof(Akce.Name));

            IList<Order> orders = _orderService.Select();
            ViewData[nameof(OrderItem.OrderID)] = new SelectList(orders, nameof(Order.Id), nameof(Order.OrderNumber));
        }
    }
}

Portal.Web/Areas/Admin/Controllers/RequestsController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Portal.Application.Abstraction;
using Portal.Domain.Entities;
using Portal.Infrastructure.Identity.Enums;

namespace Portal.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = nameof(Roles.Admin) + ", " + nameof(Roles.Manager))]
    public class RequestsController : Controller
	{
        IRequestsAdminService _requestsAdminService;
        public RequestsController(IRequestsAdminService requestsAdminService)
        {
            _requestsAdminService = requestsAdminService;
        }

        public IActionResult Requests()
        {
            IList<AdminRequest> requests = _requestsAdminService.Select();
            return View(requests);
        }

        
        public IActionResult Delete(int Id)
        {
            bool deleted = _requestsAdminService.Delete(Id);

            if (deleted)
            {
                return RedirectToAction(nameof(RequestsController.Requests));
            }
            else
                return NotFound();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            AdminRequest? adminRequest = _requestsAdminService.Select().FirstOrDefault(req => req.Id == id);

            if (adminRequest == null)
            {
                return NotFound();
            }

            return View(adminRequest);
        }

        [HttpPost]
        public IActionResult Edit(AdminRequest adminRequest)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(Solved));
            }

            return View(adminRequest);
        }

        [HttpGet]
        public IActionResult Solved(int id)
        {
            AdminRequest? adminRequest = _requestsAdminService.Select().FirstOrDefault(req => req.Id == id);

            if (adminRequest == null)
            {
                return NotFound();
            }

            return View(adminRequest);
        }

        [HttpPost]
        public IActionResult MarkAsSolved(int id)
        {
            // Uloží se stav solved
            _requestsAdminService.Update(id);
            return RedirectToAction(nameof(Requests));
        }

    }
}

Portal.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Portal.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Portal.Web.styles.css" asp-append-version="true" />
	@await RenderSectionAsync("Styles", required: false)
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portál pro prodej vstupenek</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="AkcePrehled" asp-controller="AkcePrehled" asp-action="AkceList">Akce Prehled</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						@if (User.Identity.IsAuthenticated == true && (User.IsInRole(nameof(Roles.Admin)) || User.IsInRole(nameof(Roles.Manager))))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="Akce" asp-action="Akce">Akce</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="Accounts" asp-action="Accounts">Uživatelé</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="Discussion" asp-action="Discussion">Diskuze</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="Requests" asp-action="Requests">Požadavky</a>
							</li>
							//Přidané
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="OrderItem" asp-action="Index">OrderItems</a>
							</li>
						}
						@if (User.Identity.IsAuthenticated == true && (User.IsInRole(nameof(Roles.Customer))))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" id="navbarDropdownCustomer" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Objednávky</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdownCustomer">
									
									<li class="nav-item">
										<a class="dropdown-item text-dark" asp-area="Customer" asp-controller="CustomerOrders" asp-action="Index">Historie</a>
									</li>

								</ul>
							</li>
						}
					</ul>
					<ul class="navbar-nav navbar-right">
						@{
							double totalPrice = 0;
							string totalPriceString = "TotalPrice";
							if (Context.Session != null && Context.Session.IsAvailable && Context.Session.Keys.Contains(totalPriceString))
							{
								totalPrice = Context.Session.GetDouble(totalPriceString).GetValueOrDefault();
							}
							<li class="navbar-text">
								<a class="btn btn-outline-danger" id="total_price" asp-area="Customer" asp-controller="CustomerOrderCart" asp-action="Cart">
									Košík: @totalPrice.ToString("C2")
								</a>
							</li>
						}
					</ul>
					@{
						@if (User.Identity.IsAuthenticated == false)
						{
							<ul class="navbar-nav navbar-right">
								<li class="nav-item"><a class="nav-link text-dark" asp-area="Security" asp-controller="Account" asp-action="Register"><i class="bi bi-person-plus"></i>Registrovat</a></li>
								<li class="nav-item"><a class="nav-link text-dark" asp-area="Security" asp-controller="Account" asp-action="Login"><i class="bi bi-unlock"></i>Přihlásit</a></li>
							</ul>
						}
						else
						{
							<ul class="nav navbar-nav navbar-right">
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person"></i> Přihlášen jako @User.Identity.Name</a>
									<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
										<li><a class="dropdown-item text-dark" asp-area="Security" asp-controller="Account" asp-action="Logout"><i class="bi bi-person-slash me-1"></i> Odhlásit se</a></li>
									</ul>
								</li>
							</ul>
						}
					}
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - Portal.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> | <a asp-area="Request" asp-controller="Request" asp-action="Request">Admin Request</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Portal.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Portal.Web.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portal.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Akce" asp-action="Akce">Akce</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Accounts" asp-action="Accounts">Uživatelé</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Discussion" asp-action="Discussion">Diskuze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Requests" asp-action="Requests">Požadavky</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Portal.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>